package com.stylefeng.guns.data.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sky.xposed.load.data.db.entity.HookEntity;
import com.sky.xposed.load.data.db.entity.LoadEntity;

import com.stylefeng.guns.data.db.dao.HookEntityDao;
import com.stylefeng.guns.data.db.dao.LoadEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig hookEntityDaoConfig;
    private final DaoConfig loadEntityDaoConfig;

    private final HookEntityDao hookEntityDao;
    private final LoadEntityDao loadEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        hookEntityDaoConfig = daoConfigMap.get(HookEntityDao.class).clone();
        hookEntityDaoConfig.initIdentityScope(type);

        loadEntityDaoConfig = daoConfigMap.get(LoadEntityDao.class).clone();
        loadEntityDaoConfig.initIdentityScope(type);

        hookEntityDao = new HookEntityDao(hookEntityDaoConfig, this);
        loadEntityDao = new LoadEntityDao(loadEntityDaoConfig, this);

        registerDao(HookEntity.class, hookEntityDao);
        registerDao(LoadEntity.class, loadEntityDao);
    }
    
    public void clear() {
        hookEntityDaoConfig.clearIdentityScope();
        loadEntityDaoConfig.clearIdentityScope();
    }

    public HookEntityDao getHookEntityDao() {
        return hookEntityDao;
    }

    public LoadEntityDao getLoadEntityDao() {
        return loadEntityDao;
    }

}
