package com.sky.xposed.load.data.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sky.xposed.load.data.db.entity.HookEntity;
import com.sky.xposed.load.data.db.entity.PluginEntity;

import com.sky.xposed.load.data.db.dao.HookEntityDao;
import com.sky.xposed.load.data.db.dao.PluginEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig hookEntityDaoConfig;
    private final DaoConfig pluginEntityDaoConfig;

    private final HookEntityDao hookEntityDao;
    private final PluginEntityDao pluginEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        hookEntityDaoConfig = daoConfigMap.get(HookEntityDao.class).clone();
        hookEntityDaoConfig.initIdentityScope(type);

        pluginEntityDaoConfig = daoConfigMap.get(PluginEntityDao.class).clone();
        pluginEntityDaoConfig.initIdentityScope(type);

        hookEntityDao = new HookEntityDao(hookEntityDaoConfig, this);
        pluginEntityDao = new PluginEntityDao(pluginEntityDaoConfig, this);

        registerDao(HookEntity.class, hookEntityDao);
        registerDao(PluginEntity.class, pluginEntityDao);
    }
    
    public void clear() {
        hookEntityDaoConfig.clearIdentityScope();
        pluginEntityDaoConfig.clearIdentityScope();
    }

    public HookEntityDao getHookEntityDao() {
        return hookEntityDao;
    }

    public PluginEntityDao getPluginEntityDao() {
        return pluginEntityDao;
    }

}
