package com.sky.xposed.load.data.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.sky.xposed.load.data.db.convert.ListStringConverter;
import java.util.List;

import com.sky.xposed.load.data.db.entity.PluginEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PLUGIN_ENTITY".
*/
public class PluginEntityDao extends AbstractDao<PluginEntity, Long> {

    public static final String TABLENAME = "PLUGIN_ENTITY";

    /**
     * Properties of entity PluginEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PackageName = new Property(1, String.class, "packageName", false, "PACKAGE_NAME");
        public final static Property Main = new Property(2, String.class, "main", false, "MAIN");
        public final static Property Status = new Property(3, int.class, "status", false, "STATUS");
        public final static Property HookPackageNames = new Property(4, String.class, "hookPackageNames", false, "HOOK_PACKAGE_NAMES");
    }

    private final ListStringConverter hookPackageNamesConverter = new ListStringConverter();

    public PluginEntityDao(DaoConfig config) {
        super(config);
    }
    
    public PluginEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PLUGIN_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"PACKAGE_NAME\" TEXT UNIQUE ," + // 1: packageName
                "\"MAIN\" TEXT," + // 2: main
                "\"STATUS\" INTEGER NOT NULL ," + // 3: status
                "\"HOOK_PACKAGE_NAMES\" TEXT);"); // 4: hookPackageNames
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PLUGIN_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PluginEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String packageName = entity.getPackageName();
        if (packageName != null) {
            stmt.bindString(2, packageName);
        }
 
        String main = entity.getMain();
        if (main != null) {
            stmt.bindString(3, main);
        }
        stmt.bindLong(4, entity.getStatus());
 
        List hookPackageNames = entity.getHookPackageNames();
        if (hookPackageNames != null) {
            stmt.bindString(5, hookPackageNamesConverter.convertToDatabaseValue(hookPackageNames));
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PluginEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String packageName = entity.getPackageName();
        if (packageName != null) {
            stmt.bindString(2, packageName);
        }
 
        String main = entity.getMain();
        if (main != null) {
            stmt.bindString(3, main);
        }
        stmt.bindLong(4, entity.getStatus());
 
        List hookPackageNames = entity.getHookPackageNames();
        if (hookPackageNames != null) {
            stmt.bindString(5, hookPackageNamesConverter.convertToDatabaseValue(hookPackageNames));
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PluginEntity readEntity(Cursor cursor, int offset) {
        PluginEntity entity = new PluginEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // packageName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // main
            cursor.getInt(offset + 3), // status
            cursor.isNull(offset + 4) ? null : hookPackageNamesConverter.convertToEntityProperty(cursor.getString(offset + 4)) // hookPackageNames
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PluginEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPackageName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMain(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setStatus(cursor.getInt(offset + 3));
        entity.setHookPackageNames(cursor.isNull(offset + 4) ? null : hookPackageNamesConverter.convertToEntityProperty(cursor.getString(offset + 4)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PluginEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PluginEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PluginEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
